### ISSUE TITLE
Die TeleportArea schaltet sich nach jedem Start des Spieles aus. Deshalb fliegen die Frösche durch den Boden

### ISSUE THREAD

**Issue by LH03** [4ahmnm2021-G3-G4/01-maze-audiocode-LH03#10]

**Comment by feldbacherSimone** [comment]
Hatte am anfang das gleiche problem, bei mir funktioniert es mit diesen Einstellungen, "Terrain Teleport" ist auf "Terrain" geparented

![image](https://user-images.githubusercontent.com/56028710/123546571-6fa5cf80-d75d-11eb-8af2-513b9a6174f3.png)
![image](https://user-images.githubusercontent.com/56028710/123546596-8cda9e00-d75d-11eb-889d-c75df1afda72.png)

**Comment by LH03** [comment]
Teleportation Area wird immer noch beim Spielbeginn inaktiv, aber die Frösche fliegen nicht mehr durch den Boden. Lösung: Einen MeshCollider auf den Boden gesetzt. Funktioniert zumindest im 2D Debug Modus
