### ISSUE TITLE
Die Exit Türe öffnet zu schnell bzw. die Tür springt einfach auf die falsche Stelle

### ISSUE THREAD

**Issue by LH03** [4ahmnm2021-G3-G4/01-maze-audiocode-LH03#3]

**Comment by smeerws** [comment]
Variante 1: mit Animator/Animation machen. Empty GO anlegen Türe als Kind von Empty GO anlegen.  Empty GO (Rotationspunkt an Angelpunkt von Tür schieben (sonst dreht es sich um center). Empty GO dann rotieren. 
 
Variante 2: speed verändern.
