### ISSUE TITLE
Der Trigger der Tür funktioniert nicht. Funktioniert nur wenn der Trigger berührt wird

### ISSUE THREAD

**Issue by LH03** [4ahmnm2021-G3-G4/01-maze-audiocode-LH03#4]

**Comment by smeerws** [comment]
Hier gibt es 2 Lösungsmöglichkeiten: 1) Grenzen auf der X und Z Achse anschauen, ist der HeadCollider  (X,Z) innerhalb eines Bereiches, dann Türe schliessen. BZW. Trigger in Höhe des Kopfes setzen und wie in https://github.com/HTL-SBG/FAQIssuesUnityVSGitGitHub/issues/13  testen.
