### ISSUE TITLE
Frösche bleiben während der Teleportation nur bedingt im Korb. Trigger ist vermutlich zu klein

### ISSUE THREAD

**Issue by LH03** [4ahmnm2021-G3-G4/01-maze-audiocode-LH03#6]

**Comment by smeerws** [comment]
Vermutlich kommt es zu einer race conditon, obwohl parent basket gesetzt ist, ist er in der Hierachy nicht als child ersichtlich.
Ein workaround: statt  parent in onTrigger setzen nur bool und parent in update setzten. 
 
in onTrigger einfach den bool setzten (inBasket) false bzw. true; 

-----Pseudocode

und in der **Update Methode** im Frog script 

if (inBasket)
{
gameObject.setParent(basketparentTransform)
}
else{
gameObject.setParent(null)
}

**Comment by LH03** [comment]
Skript war bei zwei Game Objekten doppelt verknüpft. Und den OnTriggerExit habe ich weggetan, weil zumindest im DebugModus das Herausnehmen der Frösche problemlos funktioniert.
